# Generated by Django 6.0.1 on 2026-06-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='Talla',
            new_name='talla',
        ),
    ]
