# Generated by Django 6.0.1 on 2026-06-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_talla_detallepedido_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varianteproducto',
            name='sku',
            field=models.CharField(help_text='Se genera automáticamente', max_length=100, unique=True),
        ),
    ]
