# Generated by Django 6.0.1 on 2026-06-24 21:53

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_varianteproducto_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombreCategoria',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagenes',
            field=models.ImageField(blank=True, help_text='Imagenes del producto en general', null=True, upload_to='productos/', validators=[api.validators.validar_tamano_imagen]),
        ),
        migrations.AlterField(
            model_name='varianteproducto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen de la variante en especifico', null=True, upload_to='variantes/', validators=[api.validators.validar_tamano_imagen]),
        ),
    ]
