# Generated by Django 6.0.1 on 2026-03-14 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_categoria_id_alter_cliente_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='categorias',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='clientes',
        ),
        migrations.AlterModelTable(
            name='instruccionescuidado',
            table='instrucciones_cuidado',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='productos',
        ),
        migrations.AlterModelTable(
            name='resena',
            table='resenas',
        ),
        migrations.AlterModelTable(
            name='stocktalla',
            table='stock_tallas',
        ),
        migrations.AlterModelTable(
            name='talla',
            table='tallas',
        ),
        migrations.AlterModelTable(
            name='tipomateria',
            table='tipos_materia',
        ),
    ]
