# Generated by Django 6.0.1 on 2026-04-01 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_categoria_table_alter_cliente_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='colaboradores/')),
                ('url', models.URLField(blank=True, help_text='Sitio web o red social del colaborador')),
            ],
            options={
                'db_table': 'colaboradores',
            },
        ),
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('horario', models.CharField(blank=True, max_length=100)),
                ('maps_embed_url', models.TextField(help_text='URL del iframe de Google Maps. Ve a maps.google.com → Compartir → Insertar mapa → copia solo el src del iframe')),
                ('maps_url', models.URLField(blank=True, help_text="URL directa de Google Maps para el botón 'Ver en Google Maps'")),
                ('es_principal', models.BooleanField(default=False, help_text='Marcar si es el punto de venta principal')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'puntos_venta',
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='producto',
            name='instruccionesCuidado',
            field=models.ManyToManyField(blank=True, related_name='productos', to='api.instruccionescuidado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tallaDisponible',
            field=models.ManyToManyField(related_name='productos', to='api.talla'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipoMateria',
            field=models.ManyToManyField(related_name='productos', to='api.tipomateria'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('colaboradores', models.ManyToManyField(blank=True, related_name='eventos', to='api.colaborador')),
            ],
            options={
                'db_table': 'eventos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='FotoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='eventos/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='api.evento')),
            ],
            options={
                'db_table': 'fotos_eventos',
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenes', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='api.producto')),
            ],
            options={
                'db_table': 'imagenes_productos',
            },
        ),
    ]
