# Generated by Django 6.0.1 on 2026-06-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_categoria_nombrecategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(blank=True, related_name='productos', to='api.categoria'),
        ),
    ]
