# Generated by Django 6.0.1 on 2026-06-03 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_colaborador_puntoventa_remove_producto_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado'), ('FALLIDO', 'Pago Fallido'), ('ENVIADO', 'Enviado')], default='PENDIENTE', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_id_sesion', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='api.cliente')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Talla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.talla')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.pedido')),
            ],
            options={
                'db_table': 'detalles_pedido',
            },
        ),
    ]
