# Generated by Django 6.0.1 on 2026-06-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de referencia del producto. Si una variante es más barata, se mostrará como descuento.', max_digits=10, null=True),
        ),
    ]
