# Generated by Django 6.0.1 on 2026-06-29 20:31

from django.db import migrations
from django.db.models import Min


def set_precio_base_from_variants(apps, schema_editor):
    Producto = apps.get_model('api', 'Producto')
    VarianteProducto = apps.get_model('api', 'VarianteProducto')

    for producto in Producto.objects.all():
        precio_min = VarianteProducto.objects.filter(
            producto=producto, activo=True
        ).aggregate(min=Min('precio'))['min']
        if precio_min is not None:
            producto.precio_base = precio_min
            producto.save(update_fields=['precio_base'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_precio_base_to_producto'),
    ]

    operations = [
        migrations.RunPython(set_precio_base_from_variants, migrations.RunPython.noop),
    ]
