# Generated by Django 6.0.1 on 2026-06-29 20:31

from django.db import migrations
from django.db.models import Min


def create_missing_tables(apps, schema_editor):
    connection = schema_editor.connection
    existing_tables = connection.introspection.table_names()

    models_in_dependency_order = [
        'Categoria', 'Talla', 'TipoMateria', 'InstruccionesCuidado',
        'Color', 'Producto', 'Cliente', 'PuntoVenta', 'Colaborador',
        'Evento', 'ImagenProducto', 'VarianteProducto', 'Resena',
        'Pedido', 'FotoEvento', 'DetallePedido',
    ]

    for model_name in models_in_dependency_order:
        model = apps.get_model('api', model_name)
        table_name = model._meta.db_table
        if table_name not in existing_tables:
            try:
                with connection.constraint_checks_disabled():
                    schema_editor.create_model(model)
            except Exception:
                pass


def set_precio_base_from_variants(apps, schema_editor):
    Producto = apps.get_model('api', 'Producto')
    VarianteProducto = apps.get_model('api', 'VarianteProducto')

    for producto in Producto.objects.all():
        precio_min = VarianteProducto.objects.filter(
            producto=producto, activo=True
        ).aggregate(min=Min('precio'))['min']
        if precio_min is not None:
            producto.precio_base = precio_min
            producto.save(update_fields=['precio_base'])


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('api', '0006_add_precio_base_to_producto'),
    ]

    operations = [
        migrations.RunPython(create_missing_tables, migrations.RunPython.noop),
        migrations.RunPython(set_precio_base_from_variants, migrations.RunPython.noop),
    ]
