# Generated by Django 6.0.1 on 2026-06-15 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pedido_detallepedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stockProducto',
        ),
    ]
