# Generated by Django 6.0.1 on 2026-06-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_producto_stockproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='stripe_id_sesion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='stripe_id_sesion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
