# Generated by Django 6.0.1 on 2026-06-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_pedido_stripe_id_sesion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='stripe_id_sesion',
            new_name='stripe_customer_id',
        ),
    ]
