# Generated by Django 6.0.1 on 2026-06-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_stripe_id_sesion_cliente_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='stripe_id_sesion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
