# Generated by Django 6.0.1 on 2026-06-22 18:10

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_pedido_stripe_id_sesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del color', max_length=50, unique=True)),
                ('codigo_hex', models.CharField(help_text='Código hexadecimal del color, ej: #FF0000 (rojo)', max_length=7, unique=True)),
            ],
            options={
                'db_table': 'colores',
            },
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='colaboradores/', validators=[api.validators.validar_tamano_imagen]),
        ),
        migrations.AlterField(
            model_name='fotoevento',
            name='foto',
            field=models.ImageField(upload_to='eventos/', validators=[api.validators.validar_tamano_imagen]),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagenes',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', validators=[api.validators.validar_tamano_imagen]),
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='productos', to='api.color'),
        ),
    ]
