# Generated by Django 6.0.1 on 2026-06-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_color_alter_colaborador_logo_alter_fotoevento_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombreCategoria',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
